/**
 * Startup environment validation.
 *
 * NOTE: As of the entrypoint.sh update, missing secrets are AUTO-GENERATED
 * at container startup. This function now only WARNS about missing vars
 * instead of throwing — preventing the app from crashing on boot.
 *
 * The entrypoint.sh script generates:
 *   - NEXTAUTH_SECRET
 *   - JWT_SECRET
 *   - JWT_REFRESH_SECRET
 *   - QR_HMAC_SECRET
 *   - ENCRYPTION_KEY
 *
 * For stable production (sessions persist across restarts), set these
 * explicitly in Coolify env vars.
 */

const REQUIRED_SECRETS = [
  'NEXTAUTH_SECRET',
  'JWT_SECRET',
  'JWT_REFRESH_SECRET',
  'QR_HMAC_SECRET',
] as const;

type RequiredSecret = typeof REQUIRED_SECRETS[number];

export function validateEnv(): void {
  const missing: string[] = [];

  for (const key of REQUIRED_SECRETS) {
    if (!process.env[key]) {
      missing.push(key);
    }
  }

  if (missing.length > 0) {
    // Warn but don't throw — entrypoint.sh should have generated these.
    // If they're still missing here, NextAuth will throw its own error
    // with a clearer message.
    console.warn(
      `⚠️ Missing env vars: ${missing.join(', ')}\n` +
      `These should be auto-generated by entrypoint.sh. If you see this in production,\n` +
      `make sure the container uses the new entrypoint.sh script.`
    );
  }
}
